(define (problem BLOCKS-5-CLEAR)
(:domain BLOCKS)
(:objects A B C D E)
(:init
    (ONTABLE A)
    (ONTABLE D)
    (ONTABLE E)
    (ON B A)
    (ON C B)
    (CLEAR C)
    (CLEAR D)
    (CLEAR E)
    (HANDEMPTY))
(:goal (AND (CLEAR A))))
